### ISSUE TITLE
VAT Notice 700/21: keeping VAT records

### ISSUE THREAD

**Issue by nelsonic** [dwyl/UK-HMRC-FAQs#5]
https://www.gov.uk/government/publications/vat-notice-70021-keeping-vat-records/vat-notice-70021-keeping-vat-records

**Comment by iteles** [comment]
:+1:

**Comment by nelsonic** [comment]
I'm having _so much fun_ this morning... :tada: :balloon:

**Comment by iteles** [comment]
It really looks like it! 🙆🏻

**Comment by nelsonic** [comment]
GOTO: https://github.com/dwyl/process-handbook/blob/master/finances.md#vat-return
